port: "5490"

postgres_username: "postgres"
postgres_password: "toster123"
postgres_port: "5432"
postgres_name: "pet_finder_user"
postgres_ssl: "disable"

mailer_service: "127.0.0.1:4490"
file_service: "127.0.0.1:4491"
